package:
  name: pybdy
  version: "0.1.0"
#source:
#  path: ../
#  git_url: https://github.com/jdha/pyBDY

build:
  preserve_egg_dir: yes
#  number: 0

requirements:
  build:
  - python
  - numpy
  - setuptools
  - scipy
  - netcdf4 >=1.1.9
  - matplotlib
  - basemap
  - thredds_crawler
  - seawater

  run:
  - python
  - numpy
  - scipy
  - netcdf4 >=1.1.9
  - matplotlib
  - basemap
  - thredds_crawler
  - seawater


#test:
#  files:
#    - ../data/grid_C/NNA_R12_bathy_meter_bench.nc
#  requires:
#    - nose
#  imports:
#    - nosetests
about:
  home: https://github.com/jdha/pyBDY
  license: GPL v3
  summary: 'NEMO Regional Configuration Toolbox'
